sizeX: 7
sizeY: 7
sizeZ: 7
blocks:
  1,4,6: minecraft:polished_blackstone_brick_stairs[facing=north,half=bottom,shape=straight,waterlogged=false]
  0,6,1: minecraft:lodestone
  0,6,0: minecraft:lodestone
  6,1,6: minecraft:lodestone
  6,1,5: minecraft:polished_blackstone_brick_stairs[facing=west,half=top,shape=straight,waterlogged=false]
  6,1,2: minecraft:polished_blackstone_brick_stairs[facing=south,half=top,shape=inner_right,waterlogged=false]
  6,1,1: minecraft:polished_blackstone_brick_stairs[facing=west,half=top,shape=straight,waterlogged=false]
  6,1,4: minecraft:polished_blackstone_brick_stairs[facing=north,half=top,shape=inner_left,waterlogged=false]
  6,1,3: minecraft:polished_blackstone_brick_slab[type=top,waterlogged=false]
  2,2,6: minecraft:polished_blackstone
  3,0,6: minecraft:smooth_stone_slab[type=top,waterlogged=false]
  3,0,5: minecraft:polished_basalt[axis=x]
  2,1,0: minecraft:polished_blackstone_brick_stairs[facing=east,half=top,shape=inner_right,waterlogged=false]
  4,6,1: minecraft:polished_andesite
  6,0,1: minecraft:lodestone
  4,6,0: minecraft:smooth_stone_slab[type=bottom,waterlogged=false]
  6,0,0: minecraft:lodestone
  4,6,3: minecraft:polished_basalt[axis=z]
  4,6,2: minecraft:netherite_block
  4,6,5: minecraft:polished_andesite
  4,6,4: minecraft:netherite_block
  5,4,6: minecraft:polished_blackstone_brick_stairs[facing=north,half=bottom,shape=straight,waterlogged=false]
  4,6,6: minecraft:smooth_stone_slab[type=bottom,waterlogged=false]
  1,3,0: minecraft:polished_blackstone_bricks
  5,4,0: minecraft:polished_blackstone_brick_stairs[facing=south,half=bottom,shape=straight,waterlogged=false]
  1,5,6: minecraft:polished_blackstone_brick_stairs[facing=north,half=bottom,shape=straight,waterlogged=false]
  0,5,0: minecraft:lodestone
  0,5,2: minecraft:polished_blackstone_brick_stairs[facing=south,half=bottom,shape=inner_left,waterlogged=false]
  0,5,1: minecraft:polished_blackstone_brick_stairs[facing=east,half=bottom,shape=straight,waterlogged=false]
  6,0,6: minecraft:lodestone
  6,0,3: minecraft:smooth_stone_slab[type=top,waterlogged=false]
  6,0,2: minecraft:smooth_stone_slab[type=top,waterlogged=false]
  6,0,5: minecraft:lodestone
  6,0,4: minecraft:smooth_stone_slab[type=top,waterlogged=false]
  2,3,6: minecraft:chiseled_polished_blackstone
  3,0,0: minecraft:smooth_stone_slab[type=top,waterlogged=false]
  3,0,4: minecraft:netherite_block
  3,0,3: minecraft:respawn_anchor[charges=0]
  3,0,2: minecraft:netherite_block
  3,0,1: minecraft:polished_basalt[axis=x]
  3,1,6: minecraft:polished_blackstone_brick_slab[type=top,waterlogged=false]
  2,2,0: minecraft:polished_blackstone
  5,5,6: minecraft:polished_blackstone_brick_stairs[facing=north,half=bottom,shape=straight,waterlogged=false]
  0,6,3: minecraft:smooth_stone_slab[type=bottom,waterlogged=false]
  0,6,2: minecraft:smooth_stone_slab[type=bottom,waterlogged=false]
  0,6,5: minecraft:lodestone
  1,4,0: minecraft:polished_blackstone_brick_stairs[facing=south,half=bottom,shape=straight,waterlogged=false]
  0,6,4: minecraft:smooth_stone_slab[type=bottom,waterlogged=false]
  0,6,6: minecraft:lodestone
  5,5,0: minecraft:polished_blackstone_brick_stairs[facing=south,half=bottom,shape=straight,waterlogged=false]
  0,0,1: minecraft:lodestone
  0,0,0: minecraft:lodestone
  0,0,3: minecraft:smooth_stone_slab[type=top,waterlogged=false]
  1,6,6: minecraft:lodestone
  0,0,2: minecraft:smooth_stone_slab[type=top,waterlogged=false]
  1,6,5: minecraft:polished_andesite
  0,0,5: minecraft:lodestone
  1,6,4: minecraft:polished_andesite
  0,0,4: minecraft:smooth_stone_slab[type=top,waterlogged=false]
  1,6,3: minecraft:lodestone
  1,6,2: minecraft:polished_andesite
  0,0,6: minecraft:lodestone
  1,6,1: minecraft:polished_andesite
  2,4,6: minecraft:polished_blackstone
  3,1,0: minecraft:polished_blackstone_brick_slab[type=top,waterlogged=false]
  3,2,6: minecraft:chiseled_polished_blackstone
  2,3,0: minecraft:chiseled_polished_blackstone
  4,0,5: minecraft:polished_basalt[axis=x]
  4,0,4: minecraft:netherite_block
  4,0,6: minecraft:smooth_stone_slab[type=top,waterlogged=false]
  5,6,6: minecraft:lodestone
  5,6,5: minecraft:polished_andesite
  5,6,4: minecraft:polished_andesite
  1,5,0: minecraft:polished_blackstone_brick_stairs[facing=south,half=bottom,shape=straight,waterlogged=false]
  5,6,3: minecraft:lodestone
  5,6,2: minecraft:polished_andesite
  5,6,1: minecraft:polished_andesite
  5,6,0: minecraft:lodestone
  6,6,5: minecraft:lodestone
  6,6,4: minecraft:smooth_stone_slab[type=bottom,waterlogged=false]
  6,6,6: minecraft:lodestone
  6,6,1: minecraft:lodestone
  6,6,0: minecraft:lodestone
  6,6,3: minecraft:smooth_stone_slab[type=bottom,waterlogged=false]
  6,6,2: minecraft:smooth_stone_slab[type=bottom,waterlogged=false]
  4,0,1: minecraft:polished_basalt[axis=x]
  4,0,0: minecraft:smooth_stone_slab[type=top,waterlogged=false]
  4,0,3: minecraft:netherite_block
  4,0,2: minecraft:netherite_block
  2,5,6: minecraft:polished_blackstone_brick_stairs[facing=east,half=bottom,shape=inner_left,waterlogged=false]
  3,2,0: minecraft:chiseled_polished_blackstone
  3,3,6: minecraft:netherite_block
  2,4,0: minecraft:polished_blackstone
  4,1,6: minecraft:polished_blackstone_brick_stairs[facing=west,half=top,shape=inner_right,waterlogged=false]
  1,6,0: minecraft:lodestone
  0,2,1: minecraft:polished_blackstone_brick_stairs[facing=east,half=top,shape=straight,waterlogged=false]
  0,2,0: minecraft:polished_basalt[axis=y]
  0,2,3: minecraft:chiseled_polished_blackstone
  6,5,6: minecraft:lodestone
  0,2,2: minecraft:polished_blackstone
  6,5,5: minecraft:polished_blackstone_brick_stairs[facing=west,half=bottom,shape=straight,waterlogged=false]
  0,2,5: minecraft:polished_blackstone_brick_stairs[facing=east,half=top,shape=straight,waterlogged=false]
  0,2,4: minecraft:polished_blackstone
  6,5,2: minecraft:polished_blackstone_brick_stairs[facing=south,half=bottom,shape=inner_right,waterlogged=false]
  6,5,1: minecraft:polished_blackstone_brick_stairs[facing=west,half=bottom,shape=straight,waterlogged=false]
  6,5,4: minecraft:polished_blackstone_brick_stairs[facing=north,half=bottom,shape=inner_left,waterlogged=false]
  6,5,3: minecraft:polished_blackstone_brick_slab[type=bottom,waterlogged=false]
  4,1,0: minecraft:polished_blackstone_brick_stairs[facing=west,half=top,shape=inner_left,waterlogged=false]
  6,5,0: minecraft:lodestone
  2,6,5: minecraft:polished_andesite
  2,6,4: minecraft:netherite_block
  2,6,6: minecraft:smooth_stone_slab[type=bottom,waterlogged=false]
  2,6,1: minecraft:polished_andesite
  2,6,0: minecraft:smooth_stone_slab[type=bottom,waterlogged=false]
  2,6,3: minecraft:polished_basalt[axis=z]
  2,6,2: minecraft:netherite_block
  3,3,0: minecraft:netherite_block
  3,4,6: minecraft:chiseled_polished_blackstone
  2,5,0: minecraft:polished_blackstone_brick_stairs[facing=east,half=bottom,shape=inner_right,waterlogged=false]
  4,2,6: minecraft:polished_blackstone
  0,3,6: minecraft:polished_basalt[axis=y]
  0,3,5: minecraft:polished_blackstone_bricks
  5,0,6: minecraft:lodestone
  5,0,5: minecraft:polished_basalt[axis=y]
  5,0,4: minecraft:polished_basalt[axis=z]
  5,0,3: minecraft:polished_basalt[axis=z]
  0,1,0: minecraft:lodestone
  5,0,2: minecraft:polished_basalt[axis=z]
  5,0,1: minecraft:polished_basalt[axis=y]
  0,1,2: minecraft:polished_blackstone_brick_stairs[facing=south,half=top,shape=inner_left,waterlogged=false]
  5,0,0: minecraft:lodestone
  0,1,1: minecraft:polished_blackstone_brick_stairs[facing=east,half=top,shape=straight,waterlogged=false]
  0,1,4: minecraft:polished_blackstone_brick_stairs[facing=north,half=top,shape=inner_right,waterlogged=false]
  0,1,3: minecraft:polished_blackstone_brick_slab[type=top,waterlogged=false]
  6,4,6: minecraft:polished_basalt[axis=y]
  0,1,6: minecraft:lodestone
  0,1,5: minecraft:polished_blackstone_brick_stairs[facing=east,half=top,shape=straight,waterlogged=false]
  1,1,6: minecraft:polished_blackstone_brick_stairs[facing=north,half=top,shape=straight,waterlogged=false]
  6,4,3: minecraft:chiseled_polished_blackstone
  6,4,2: minecraft:polished_blackstone
  6,4,5: minecraft:polished_blackstone_brick_stairs[facing=west,half=bottom,shape=straight,waterlogged=false]
  6,4,4: minecraft:polished_blackstone
  6,4,1: minecraft:polished_blackstone_brick_stairs[facing=west,half=bottom,shape=straight,waterlogged=false]
  4,2,0: minecraft:polished_blackstone
  6,4,0: minecraft:polished_basalt[axis=y]
  3,4,0: minecraft:chiseled_polished_blackstone
  3,5,0: minecraft:polished_blackstone_brick_slab[type=bottom,waterlogged=false]
  3,5,6: minecraft:polished_blackstone_brick_slab[type=bottom,waterlogged=false]
  4,3,6: minecraft:chiseled_polished_blackstone
  1,0,6: minecraft:lodestone
  0,2,6: minecraft:polished_basalt[axis=y]
  1,0,5: minecraft:polished_basalt[axis=y]
  1,0,4: minecraft:polished_basalt[axis=z]
  1,0,3: minecraft:polished_basalt[axis=z]
  5,1,6: minecraft:polished_blackstone_brick_stairs[facing=north,half=top,shape=straight,waterlogged=false]
  1,0,2: minecraft:polished_basalt[axis=z]
  1,0,1: minecraft:polished_basalt[axis=y]
  1,0,0: minecraft:lodestone
  5,1,0: minecraft:polished_blackstone_brick_stairs[facing=south,half=top,shape=straight,waterlogged=false]
  0,4,1: minecraft:polished_blackstone_brick_stairs[facing=east,half=bottom,shape=straight,waterlogged=false]
  0,4,0: minecraft:polished_basalt[axis=y]
  0,4,3: minecraft:chiseled_polished_blackstone
  1,2,6: minecraft:polished_blackstone_brick_stairs[facing=north,half=top,shape=straight,waterlogged=false]
  0,4,2: minecraft:polished_blackstone
  6,3,4: minecraft:chiseled_polished_blackstone
  6,3,3: minecraft:netherite_block
  6,3,6: minecraft:polished_basalt[axis=y]
  6,3,5: minecraft:polished_blackstone_bricks
  6,3,0: minecraft:polished_basalt[axis=y]
  4,3,0: minecraft:chiseled_polished_blackstone
  6,3,2: minecraft:chiseled_polished_blackstone
  6,3,1: minecraft:polished_blackstone_bricks
  2,0,6: minecraft:smooth_stone_slab[type=top,waterlogged=false]
  3,6,2: minecraft:polished_basalt[axis=x]
  3,6,1: minecraft:lodestone
  3,6,0: minecraft:smooth_stone_slab[type=bottom,waterlogged=false]
  3,6,6: minecraft:smooth_stone_slab[type=bottom,waterlogged=false]
  3,6,5: minecraft:lodestone
  3,6,4: minecraft:polished_basalt[axis=x]
  4,4,0: minecraft:polished_blackstone
  4,4,6: minecraft:polished_blackstone
  0,5,4: minecraft:polished_blackstone_brick_stairs[facing=north,half=bottom,shape=inner_right,waterlogged=false]
  0,5,3: minecraft:polished_blackstone_brick_slab[type=bottom,waterlogged=false]
  0,5,6: minecraft:lodestone
  5,2,6: minecraft:polished_blackstone_brick_stairs[facing=north,half=top,shape=straight,waterlogged=false]
  0,5,5: minecraft:polished_blackstone_brick_stairs[facing=east,half=bottom,shape=straight,waterlogged=false]
  1,1,0: minecraft:polished_blackstone_brick_stairs[facing=south,half=top,shape=straight,waterlogged=false]
  5,2,0: minecraft:polished_blackstone_brick_stairs[facing=south,half=top,shape=straight,waterlogged=false]
  0,3,0: minecraft:polished_basalt[axis=y]
  0,3,2: minecraft:chiseled_polished_blackstone
  0,3,1: minecraft:polished_blackstone_bricks
  1,3,6: minecraft:polished_blackstone_bricks
  0,3,4: minecraft:chiseled_polished_blackstone
  0,3,3: minecraft:netherite_block
  6,2,5: minecraft:polished_blackstone_brick_stairs[facing=west,half=top,shape=straight,waterlogged=false]
  6,2,4: minecraft:polished_blackstone
  6,2,6: minecraft:polished_basalt[axis=y]
  6,2,1: minecraft:polished_blackstone_brick_stairs[facing=west,half=top,shape=straight,waterlogged=false]
  6,2,0: minecraft:polished_basalt[axis=y]
  6,2,3: minecraft:chiseled_polished_blackstone
  6,2,2: minecraft:polished_blackstone
  2,1,6: minecraft:polished_blackstone_brick_stairs[facing=east,half=top,shape=inner_left,waterlogged=false]
  2,0,3: minecraft:netherite_block
  2,0,2: minecraft:netherite_block
  2,0,5: minecraft:polished_basalt[axis=x]
  2,0,4: minecraft:netherite_block
  2,0,1: minecraft:polished_basalt[axis=x]
  2,0,0: minecraft:smooth_stone_slab[type=top,waterlogged=false]
  4,5,0: minecraft:polished_blackstone_brick_stairs[facing=west,half=bottom,shape=inner_left,waterlogged=false]
  6,1,0: minecraft:lodestone
  4,5,6: minecraft:polished_blackstone_brick_stairs[facing=west,half=bottom,shape=inner_right,waterlogged=false]
  0,4,5: minecraft:polished_blackstone_brick_stairs[facing=east,half=bottom,shape=straight,waterlogged=false]
  0,4,4: minecraft:polished_blackstone
  5,3,6: minecraft:polished_blackstone_bricks
  0,4,6: minecraft:polished_basalt[axis=y]
  1,2,0: minecraft:polished_blackstone_brick_stairs[facing=south,half=top,shape=straight,waterlogged=false]
  5,3,0: minecraft:polished_blackstone_bricks
